#!/bin/sh
# Short script to copy the required files from bioplib for creation
# of a distribution version of KabatMan
# V1.0  10.05.94 By: ACRM
# V1.1  11.05.94 Added general.h
# V1.2  13.05.94 Code only
# V2.0  07.07.94 Code only
# V2.3  25.01.95 Code and separate src directory
# V2.5  10.03.95 Code and now copies patchkabat.perl
# V2.6  04.10.19 Added data directory and kabattest

BIOP=${HOME}/git/bioplib/src
KABMAN=KabManV2.26
KABSRC=$KABMAN/src
KABTST=$KABMAN/kabattest
KMBIOP=$KABSRC/bioplib
KMDATA=$KABMAN/data

# Create subdirectories
if [ -d $KABMAN ]
then
   echo "Got KabatMan directory"
else
   echo "Creating KabatMan directory"
   mkdir $KABMAN
fi

if [ -d $KABTST ]
then
   echo "Got kabattest directory"
else
   echo "Creating kabattest directory"
   mkdir $KABTST
fi

if [ -d $KABSRC ] 
then
   echo "Got source sub-directory"
else
   echo "Creating source sub-directory"
   mkdir $KABSRC
fi

if [ -d $KMBIOP ] 
then
   echo "Got bioplib sub-directory"
else
   echo "Creating bioplib sub-directory"
   mkdir $KMBIOP
fi

if [ -d $KMDATA ] 
then
   echo "Got data sub-directory"
else
   echo "Creating data sub-directory"
   mkdir $KMDATA
fi

# Copy bioplib files into directory
cp ${BIOP}/array2.c       $KMBIOP
cp ${BIOP}/array.h        $KMBIOP
cp ${BIOP}/deprecated.h   $KMBIOP
cp ${BIOP}/DNAtoAA.c      $KMBIOP
cp ${BIOP}/general.h      $KMBIOP
cp ${BIOP}/GetFilestem.c  $KMBIOP
cp ${BIOP}/GetWord.c      $KMBIOP
cp ${BIOP}/hash.h         $KMBIOP
cp ${BIOP}/KnownSeqLen.c  $KMBIOP
cp ${BIOP}/macros.h       $KMBIOP
cp ${BIOP}/MathType.h     $KMBIOP
cp ${BIOP}/pdb.h          $KMBIOP
cp ${BIOP}/QueryStrStr.c  $KMBIOP
cp ${BIOP}/seq.h          $KMBIOP
cp ${BIOP}/SysDefs.h      $KMBIOP
cp ${BIOP}/throne.c       $KMBIOP
cp ${BIOP}/TrueSeqLen.c   $KMBIOP
cp ${BIOP}/upstrcmp.c     $KMBIOP
cp ${BIOP}/upstrncmp.c    $KMBIOP

# Copy source code into directory
cp ./src/*.c ./src/*.h ./src/*.p  $KABSRC

# Copy install script into directory
cp install.sh         $KABMAN

# Copy documentation into directory
cp README.md          $KABMAN

# Copy in the patchkabat program
cp patchkabat.perl    $KABMAN

# Copy data and kabattest
cp ./data/*           $KMDATA
cp ./kabattest/*      $KABTST

# Copy distribution specials into directory
cp ./src/Makefile.dist $KABSRC/Makefile

# Tar up the distribution directory
tar -cvf ${KABMAN}.tar $KABMAN
gzip ${KABMAN}.tar

# and finally delete the directory
/bin/rm -rf $KABMAN

